### model
model_name_or_path: silx-ai/Quasar-ant

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: quasar
template: qwen
cutoff_len: 32768
overwrite_cache: true
preprocessing_num_workers: 16
packing: true
### output
output_dir: saves/llama3-8b/full/sft
logging_steps: 2
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: wandb
### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
save_only_model: true
